image:
  repository: wlanboy/javahttpclient
  tag: latest
  pullPolicy: Always

replicaCount: 1
deploymentname: javahttpclient
namespace: clients

service:
  name: javahttpclient-svc
  type: ClusterIP
  port: 8080
  targetPort: 8080

volume:
  mountPath: /tmp

hosts: 
  - javahttpclient.tp.lan
  - javahttpclient.gmk.lan

istio:
  gatewayName: javahttpclient-gw
  gatewayNamespace: "istio-ingress"
  tls:
    enabled: true
    secretName: javahttpclient-tls

certManager:
  enabled: true
  issuerRef:
    kind: ClusterIssuer
    name: "local-ca-issuer"
  dnsNames:
    - javahttpclient.tp.lan
    - javahttpclient.gmk.lan
