apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentname }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentname }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentname }}
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: {{ .Values.deploymentname }}-sa
      containers:
        - name: {{ .Values.deploymentname }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/application.properties
              subPath: application.properties
            - name: tmp-volume
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.deploymentname }}-config
        - name: tmp-volume
          emptyDir: {}