apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.deploymentname }}-diagnostic-role
  namespace: {{ .Release.Namespace }}
rules:
  # Standard Ressourcen für den Kontext
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]

  # Istio spezifische Ressourcen für die Netzwerkanalyse
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices", "destinationrules", "sidecars", "gateways", "serviceentries", "envoyfilters"]
    verbs: ["get", "list", "watch"]

  # Istio Security Ressourcen (AuthorizationPolicy/PeerAuthentication/RequestAuthentication)
  - apiGroups: ["security.istio.io"]
    resources: ["authorizationpolicies", "peerauthentications", "requestauthentications"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.deploymentname }}-diagnostic-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.deploymentname }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.deploymentname }}-diagnostic-role
  apiGroup: rbac.authorization.k8s.io

