apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "java-http-client.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java-http-client.labels" . | nindent 4 }}
automountServiceAccountToken: true